FROM python:3.14.2
WORKDIR /app
COPY ./frontend/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./frontend/interface.py
CMD ["streamlit", "run", "interface.py", "--server.port=8501", "--server.address=0.0.0.0"]