FROM python:3.12-slim
WORKDIR /app
COPY ./backend/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./backend/app .
COPY ./backend/model ./model
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]