FROM python:3.14.2
WORKDIR /app
COPY ./backend/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./backend /app
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]